### ISSUE TITLE
FINV のテーブルを修正する

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#1]
神資料によると、 finv の誤差は 4ulp であれば十分だそうですが、現状 6 ulp くらいです。
テーブルの最適化をやりなおすことで、この誤差を縮小してください。

これは fdiv の仕様を満たすために必要な処理です。 fmul にも誤差があるので、 `fmul * finv` で fdiv を求めているため、誤差が拡大します。

すべきことは 「fpu/software/finv_ikuta.cc を、コードはそのままでテーブルを変更して誤差を修正する」です。

finv は総当たりが可能なので、仮数部が 0 から 0x7fffff までを総当たりして結果が 4ulp 以内におさまることを確認してください。

`sumDiff` が補正用に作った関数なので、ロジックは適当ですが、枠組みは利用できるかと思います。

**Comment by bch3dal** [comment]
現段階での進捗状況です。
誤差の大きかった行について、定数項const,A1一次の項incのテーブルを手で書き直して
できたfinv.datは、誤差が±4ulpに収まりました。が、mips/以下に上がっているfinv.datと比べ分散が大きいのと
どうも手で書いたので山の中心が+1ulp近辺にずれているようです。

また神資料を参考にしながら最適化関数を書いて、初期状態のconst,incテーブルに適用して作ったfinvは、
まだ±5ulpの誤差が出ています。

**Comment by tomykaira** [comment]
すみません、4ulp以内と書いていましたが、神資料をみなおしたら 4ulp _未満_ のようです。

いま出ている結果はどちらでしょうか?

b8c5e37fafdff2721c9963586426797f34272974 でスライドに進捗を載せました。なにか訂正すべき点があれば今日中におねがいします。

**Comment by bch3dal** [comment]
せめて手修正の方だけでも何とか±3ulp以内に…と思ったのですが、どういじってみてもテーブルの上の方が±4ulpですね…。
最適化関数の方も同様で、150行め以降は定数項を補正するだけで結構まとまるのですが、3~40行め前後の最適化がうまくいっていません。以下現在の誤差状況です。
手打ち修正: ±3ulp以下/8384977  ±4ulp/3631  ±5ulp以上/0
最適化関数: ±3ulp以下/8357217  ±4ulp/30769  ±5ulp/622  ±6ulp以上/0

**Comment by tomykaira** [comment]
了解です。現段階ではこれで問題ないと思います。
来週（次々回)の発表のネタにしてもらってもいいですよ。

スライドに数字を反映しておきました。

**Comment by bch3dal** [comment]
手打ち、±4を259casesまで減らしました（先ほどプレゼン用資料に反映しました）が、
ここからなかなか減らないです。2種のテーブルの値を1ずつ書き換えてもまだ微妙なラインです。
テーブルの各行は互いに影響を与えないはずですが、同じ定数項一次項の組み合わせでも集計結果が
なぜか異なるという現象が2,3度あったため、チェック段階で余計なことをしていないか等もう一度確認します。
手打ちテーブルは今も修正していますが、ここから少し最適化関数の方にシフトしていきます。

**Comment by bch3dal** [comment]
finvの誤差が-4ulpだった675caseについて、fdivで誤差を計算する案がありましたが、
実際計算してみると総当たりでは厳しそうです。
被除数に何も制限がないため2^32は必ずかかる＋1000caseのチェックに18秒かかる
＝8.7*10^5[year]かかる見込み
fmulで使ったrandomcaseを使ってみます。

**Comment by tomykaira** [comment]
random でいいと思います。

どういう状況かわからないのですが、もしクリティカルな領域が判断できれば、そこにたいして実証すればなお良いです。
A/B にたいして、Bを固定したとき、A と仮数部の誤差の相関関数を考えて、それの極大にたいして 8ulp 以下であることが証明できれば正しく実装されていることを主張できます。

**Comment by bch3dal** [comment]
後で卜部さん宛にも報告送りますが、一応先週fdivを作ってみたのでここにも記録しておきます。
finvの誤差が-4ulpだった仮数部のパターンを抜き出し、それにrandomに指数部他を補ったbと
完全にrandomで取ってきたaとでa/bを計算したところ、20000000caseが±5ulpに収まりました。
（2^-127<a/b<2^127に収まらなかった計算を除外した場合）

**Comment by bch3dal** [comment]
finvまわり、改良版をようやくリポジトリに上げました。
最適化チェックをして、十分であることを確認してからだいぶ経ってしまい申し訳ありませんでした。
とりあえずこのリクエストも閉じておきます。
