### ISSUE TITLE
floating 演算の誤差

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#14]
うらべさんの fractal-flame ブランチで、浮動小数まわりのどこか(たぶん read_float?)の誤差が拡大しているようなのですが、心当たりありますか?
たとえば `compiler_set/test/Loreley/test/read_deConf.ml` で 0.4 を読んで10000倍して 4000 を出力するテストで、 3999 が出力されて失敗します。

さすがにこれは許容できないですが、丸めの方法を変更するなどによってこのような問題が出る場合はあると思うので、
浮動小数としての誤差と(4000.5 より 3999.9 のほうが精確とかそういう話)、 read_float -> print_float の流れが失敗する理由を調査したいです。

もし心当たりがあれば教えてください。なかったら @bch3dal さんにデバッグをおねがいしたいです。

**Comment by urabenatsuki** [comment]
心当たりはあります。
今までライブラリ関数のint_of_floatは小数を切り上げていたのですが、
fractal flameの中に浮動小数の計算結果を丸めて配列のインデクスを計算している箇所があり、
切り上げると配列の範囲をはみ出してしまうために切り捨てに変えました。
変更を伝えていなくてすみませんでした。

**Comment by tomykaira** [comment]
なるほど。了解しました。
ocaml の `int_of_float` はそうなんですよね。

この変更は min-caml のレギュレーションに違反しませんか?(要求は最近接整数なので)
`0.4 *. 10000` が 4000 にならないのも嫌な気がします。

他の計算誤差が大きいからか、ほんらい一致すべき箇所で OCaml と結果が一致しなくなっているのも問題に感じるので、
この件は TA にフィードバックしたほうがよさそうです。
お願いしてもいいでしょうか?面倒だったらFPU係に振ってください。

もし必要があれば round と int_of_float を分けることになります。

そのあたりの事情がわかったらテストケースを作りなおします。

**Comment by urabenatsuki** [comment]
int_of_floatについてはとりあえずTAにメールを送りました。
04 *. 10000. が4000にならない件についてですが、read_floatを介さず、直接配列に0.4を代入しそれを10000倍して出力する
プログラムをコンパイルしてみたところ、こちらは4000と表示されました。
配列に代入された値の畳み込みは行っていません。

**Comment by tomykaira** [comment]
これはどちらに寄せることになったんですか？

**Comment by urabenatsuki** [comment]
昨日TAから話があって、fractal_flameの時だけocamlに合わせるとのことでした。

**Comment by tomykaira** [comment]
了解です。テストファイルの先頭になにかコメントで書いておくと、それに応じてライブラリを変更するような仕組みを作ります。
