### ISSUE TITLE
PS/2キーボードの資料さがし

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#17]
ディスプレイが使えるようになったので、キーボードを使いたいです。
USB よりは PS/2 のほうが楽なのではないかな?と思っています。
くわしいやりたいことについては直接会った時にはなします。

仕様書を探しておいていただけると助かります。

**Comment by bch3dal** [comment]
とりあえずPS/2キーボードの仕様書の原文は以下にあるようです。
http://www.computer-engineering.org/

**Comment by tomykaira** [comment]
なるほど、ほぼ RS232C とおなじですね。
参考になりました。ありがとうございます。

自分用のメモとして、いくつか参照できるものを並べておきます。

[The PS/2 Mouse/Keyboard Protocol](http://www.computer-engineering.org/ps2protocol/)
[The PS/2 Keyboard Interface](http://www.computer-engineering.org/ps2keyboard/)
[PS2 Keyboard Mouse Protocols Port Auxiliary Device System Timings Data Sent](http://www.networktechinc.com/ps2-prots.html)
[Scan Codes -- Set 2](http://www.computer-engineering.org/ps2keyboard/scancodes2.html)
