### ISSUE TITLE
シミュレータにメトリクス機能を追加

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#18]
- どの命令が何回つかわれているのか
- どれくらいヒープが使われたか
- 最大でどれくらいスタックが使われたか
- 最大メモリ消費量(スタック+ヒープの最大値)
- 最大でどれくらいの深さの関数呼び出しがおこなわれたか

などのメトリクスを取る機能がほしいです。
命令の最適化などのためです。

もし時間とやるきがあれば手伝ってほしい、というかんじです。

**Comment by bch3dal** [comment]
とりあえず昨日の段階で命令種別のカウント機能だけ実装しています。

**Comment by tomykaira** [comment]
ありがとうございます。

現時点のものをマージしようとしたのですが、
cpp ファイルのインデントがかわってしまっているようですので、不要な変更をしないように作業してもらえますか?
マージの時にじっさいに変更されたのがどこかがわからなくなり、マージ漏れが出てきてしまう事がおおいためです。
注意して編集するのは面倒で申し訳ないのですが。。
emacs なら設定でインデントの取りかたを変えることができたと思います。調べてみてください。

git でコミットする前に git diff で変更分を確認し、変更したつもりのない行が変更されていないことを確認すると便利です。
