### ISSUE TITLE
シミュレータを新しいISAに対応させる

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#19]
いくつかの変更をくわえましたので、コンパイラとコアが意思疎通するツールとしてのシミュレータをアップデートしてください。
- いくつかの命令の削除(mul,and,or,nor,muli,andi,ori,nori,bne,fbne,fmov,fneg)
- f0 は定数0レジスタ(fmov,fneg は 0 と fadd, fsub で代用するようにするという方針です。これだと計算時間が余計にかかるという問題はあるので、よびだし回数が多いことがわかれば復活します)
- fmvhi は下位16ビットに0を入れる

@rnatori さんがやっていただいてもかまいません。
この作業は必ず別のブランチでやっていただくようおねがいします。

**Comment by bch3dal** [comment]
とりあえず作業用のブランチを作成しました。
また、なんとかocaml3.12.1でコンパイラのコンパイルができました。

シミュレータを書き換える前に確認なのですが、現在のシミュレータはmake testをするといくつかサンプルをテストした後に
tee:書き込みエラー
を吐いて落ちる挙動で問題ないですよね?

**Comment by tomykaira** [comment]
お疲れさまでした。セットアップお手数おかけして申し訳ありません。

tee のエラーは原因不明ですが、本プロジェクトとは関係ありません。
`| tee` を  `>` で置き換えておいてください。それで動作すれば OK です。

いずれプロジェクト全体で修正します。

**Comment by tomykaira** [comment]
ちなみに、ISA は現在 google docs にあがっているものからさらに変更が入っています。

自分でもよくわからないので、なにかツールを作って整理するつもりでいます。

二度手間になってしまいそうな気がすごくしていますので、 @u-natsuki さんの要望の高いものから作っていったほうがいいかもしれません。

**Comment by bch3dal** [comment]
リダイレクションにすれば動作するようです。

単純にsimulatorとassemblerから該当部を削除しても、
コンパイルされたコードにはまだmulやfnegなどが残りますよね。
（そしてアセンブラが「こんな命令知らない」と返す。）

今回の修正は、
・simulator.cppを書き直し（該当命令を削除）
・assembler.cppのなかで、コンパイル済みのコードにmulやfneg等が入っていたら
ISAに残っている他の命令の組み合わせに変換して出力するように変更

…と言う形になるのでしょうか？
まぁ、自分は余計なところをいじらずにメトリクス機能の実装をしたほうがいいのかもしれませんが。

**Comment by tomykaira** [comment]
コンパイラ側の対応は済んでいます。(https://github.com/tomykaira/mips/pull/21)
新しい命令セットへの書き換えは assembler だけではできず、レジスタ割り当てなどにコンパイラの助けを借りる必要がありますので、 assembler での命令の書き換えは実装の必要ありません。
エラーを出すに留めてください。

もしかしたらライブラリで置き換えが必要な部分があるかもしれません。
これについてはうらべさんと話しつつ、適宜新しい命令セットのもので置換してください(min-rt が動作するそうなので、問題ないと思いますが)。

**Comment by bch3dal** [comment]
メールでの件了解です。sim_updateは、命令種の削減の他は基本的にシミュレータの命令種別カウントが実装されただけなので、マージの際はほとんどmasterのもので上書きしてしまってよいと思います。

ディスプレイ出力のイメージがつかめない
(=simulatorのなかでどこの情報を監視すればよいのか分からない)ので、画面表示機能まだ時間かかりそうです。

**Comment by tomykaira** [comment]
私が作った版はまあ問題なく動作するのでマージしました。

> ディスプレイ出力のイメージがつかめない(=simulatorのなかでどこの情報を監視すればよいのか分からない)ので、画面表示機能まだ時間かかりそうです。

うらべさんにはイメージをおつたえしてあるので、適当に話してきめてもらえればいいです。
最低限の機能は描画命令が呼ばれるたびに、描画バッファ(80x24要素ぐらいの配列)の内容を画面に書き出すことです。
