### ISSUE TITLE
プレゼンテーションソフトの作成

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#20]
例の件です。
他に危急の課題がなくなったらとりかかってください。

80x24 の画面上の位置を指定して ASCII 文字を印字するようなイメージです。

実装方法についてはまだ悩んでいます。書き出し専用命令かメモリを共有するかのどちらかですが、たぶん書き出し専用命令にします。

**Comment by tomykaira** [comment]
おそくなりましたが、プレゼンソフトのソースを確認しました。

現在は改ページのたびに処理をとめ、キー入力があってから再開するような構成ですが、プレゼンデータの読み込みだけは最初におわらせるように変更してもらえますか?
デモとして、PCと接続せずに動作していることをアピールしたいからです。
大変そうだったらべつにかまいません。
検討よろしくおねがいします。

まだ実機確認できていないのでリポジトリに反映していませんが、描画命令を実装しました。
バッファサイズは通常モードで 80*30 になりました。もしこれで字がちいさすぎるなどの問題があれば、プレゼンモードで 40x15 を用意するかもしれません。
もしここらへんの値で調整が必要ならお願いします。

**Comment by urabenatsuki** [comment]
変更しました。
入力ファイルは、総ページ数 + 1頁目 + -1 + 2頁目 + ... + n頁目 + -1 の形式です。
readkbdを行う回数だけファイル末尾に余分な文字をつけないとシミュレータがエラーを吐くので余分な文字を入れてあります。

**Comment by tomykaira** [comment]
ありがとうございます。動作が確認できたのでマージしました。
