### ISSUE TITLE
班の名前を决める

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#3]
5班というのは微妙なのでおもしろい班の名前をつけましょう。

班長さんにわりあてておきます。地下でわいわいやって決めてください。

**Comment by bch3dal** [comment]
結局わいわいするほどの人数は集まりませんでしたのでちょっと話しあっただけです。周りからは単位班とかいろいろ言われていましたが、それはそれで被りそうなので完動班でいいんじゃないですか？

もっとも完動はひとえにtomyさんの功績なので承認が得られないならばまた別のになるでしょうけども。

**Comment by tomykaira** [comment]
私はそれでかまいません。他に意見のある人は今日中におねがいします。

**Comment by bch3dal** [comment]
班名については「完動班」で決定します。
