### ISSUE TITLE
文字ビットマップの用意

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#31]
16x8 の 0/1 の文字を用意してください。

たとえば

```
        |
   11   |
   11   |
  1  1  |
  1  1  |
  1  1  |
  1  1  |
 1    1 |
 1    1 |
 1    1 |
 1    1 |
11111111|
1      1|
1      1|
1      1|
1      1|
```

のようなかんじです(| は範囲を示すためのマーカです)。

最低限英語の小文字。これは週末までにおねがいします。

できれば次の文字種は用意したいです。

! " # $ % & ' ( ) \* + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? @ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z [ \ ] ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z { | } ~

**Comment by tomykaira** [comment]
文字の周囲（上下左右）に余白を１列とるように心がけると良さそうです。

**Comment by bch3dal** [comment]
文字ごとにuint8_t[16]みたいに定義しておけばよいでしょうか？
それと、今週週末、駒場祭とは全く無関係に金土日とサークル活動で埋まってしまったのでシミュレータの遅延スロット対応は厳しそうです…。とりあえずすぐできそうなこちらだけ仕上げておきます。

**Comment by tomykaira** [comment]
コアに埋め込むので、冒頭とおなじテキスト形式でいただけるとありがたいです。
後でいじる時もそのほうが楽なので。

ファイルフォーマットはまかせますが、特殊文字があるのでファイルごとにはできなそうです。

```
A
        |
   11   |
   11   |
  1  1  |
  1  1  |
  1  1  |
  1  1  |
 1    1 |
 1    1 |
 1    1 |
 1    1 |
11111111|
1      1|
1      1|
1      1|
1      1|
B
Bの字形
```

のような形でもらえると、機械処理しやすいでしょうか。

いろいろ注文をつけてすみませんが、よろしくおねがいします。

遅延スロットはまだ先で大丈夫です。
シミュレータはかなりくさっているので、今の状態を改造して実装するのは大変そうです。
できればもっと見通しよく書き直したいなと思っています。
なので、時間があれば私がタスクもらいます。

**Comment by bch3dal** [comment]
とりあえずmasterにあげてしまいました。
元にした表形式のファイルも一緒にあげたので、形を直すときは両方直すとわかりやすいかなと思います。
一応ベースラインを意識したつもりですが、見にくい等不都合ありましたら直しちゃってください。

**Comment by tomykaira** [comment]
すばらしい！作業が早くて助かります。
