### ISSUE TITLE
自家製コンパイラで動作させる

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#5]
いくら遅くてもいいので、正しい命令を吐いて、min-rt が動作することを目指しましょう。
シミュレータで動作するところまでを確認してください。
- できそう
- できなさそう
- ここがよくわからない

とかがあれば相談しましょう。

**Comment by urabenatsuki** [comment]
現在の進捗状況を報告します。
とりあえずシミュレータ上で fib.ml が動くようになりました。
ただ、min-rt をコンパイルしようとするとなぜか型の単一化の際にエラーが出るので
原因を究明中です。

**Comment by tomykaira** [comment]
おつかれさまです。

もしヘルプ必要だったら課題の解答にもなりそうなのでやります、投げてください。

ひととおり終わったら、mimic ではなくこのリポジトリにディレクトリを作成して置いてもらえますか。
mimic はだんだんメンテしなくするつもりなので。

**Comment by urabenatsuki** [comment]
一応min-rtがシミュレータ上で動くようになりました。
ただ、課題用のmin-rtのコードは多相型を持つ関数を使うように書き直されており、多相型を実装しないと
動かないようになっているのですが、多相型の実装は後日コンパイラ係向け課題として出るということなので
ここではとりあえずこの関数だけパージングの段階で特別扱いして型エラーを回避し、多相型はまだ実装していません。

**Comment by tomykaira** [comment]
すみません、現状のコンパイル方法と実行方法をドキュメント化していただけますか。

min-caml 添付の fib.ml を実行しようとしたところ、 `print_char` が実装されていないようなのですが、これはどうする予定でしょう?
もしなにか見落していたらすみません。

**Comment by urabenatsuki** [comment]
ドキュメント化したものを追加しました。

print_char は,既存のライブラリに追加したのを忘れていたのでこれも追加しました。すみませんでした。

**Comment by tomykaira** [comment]
いまはバイナリ入力とテキスト入力をコードを編集することで切り替えているようですが、
本番の cserver の送信するのがバイナリなので、コンパイラにオプションをつけられるようにできますか?

たんにデフォルトバイナリ版にするのでも OK です。

**Comment by tomykaira** [comment]
実機動作しました。

```
receiving PPM data:
        version: 3       size: 128x128
        received 16384/16384 pixels.
        done.
elapsed time : 210.339664 s  
```

シミュレータとの出力も一致しています。

この速さでこれだけ速いバイナリを作るのはすごいと思います。おつかれさまでした!!

**Comment by urabenatsuki** [comment]
オプションをつけられるようにしました。
-b とオプションをつけると,入力をバイナリファイルから受けとるようになります。

**Comment by tomykaira** [comment]
すみません、 google docs の mimic2 specification に一箇所まちがいがありました。

fsti のところに取り消し線が引かれて、使用できないことになっていましたが、これは str のまちがいでした。
fsti は使用できます。

**Comment by tomykaira** [comment]
終わったぽいので閉じます
