### ISSUE TITLE
greenS が無限ループする

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#58]
pc: 162 あたりをまわっています。

tailed さんが発表していた問題と関連していると思われますので、問合せ中です。
おそらく loreley 本体を書き換える必要があります。その上でさらに問題があったら直してください。

**Comment by tomykaira** [comment]
tailed さんにもらった訂正版をもとに訂正したものを cache_memory_sim ブランチに置いておきました。

いまだに無限ループするみたいなので、対応をおねがいします。

**Comment by urabenatsuki** [comment]
現状の報告をします。とりあえず以下の点を変更しました。
1. int_of_floatには引数が8388608.0未満になるまで8388608.0を引き続ける処理があり、
　無限ループ（に見えたもの）の原因は関数expがint_of_floatに非常に大きい数を渡していたことであった。
　そこで、expに、引数が非常に大きい場合は0x7F800000を、小さい場合は0を返す処理を追加。
2. sinにも同様に引数が2π以下になるまで2πを引き続ける処理があって、1.を直したところ今度はこれが
　無限ループ？の原因となったので神資料にあった実装に変更。
3. 累乗の実装を修正。
以上の点について問題があったら言ってください。

ただ、これらを修正してもまだgreenSは正常に動きません。
Loreleyの関数create_deFilterでは

let max_rad=deConf.(0)_.conf.(2) in
let kernel_size=int_of_float ((max_rad+.1.0)_.(max_rad+.2.0)/.2.0) in
deCoeffs:=Array.make (kernel_size*max_index_count) 0.0;

として(1+2+...+(max_rad+1))*max_index_countのサイズの配列を生成した上で、

  let rec createFilter pos cIndex=
    let rec setDeCoeffs x y index sumWeight=
       if y<=x then
          (let tmp=(sqrt (x_.x+.y_.y))/.(deWidth pos) in
           if tmp<=1.0 then !deCoeffs.(index) <- (gauss tmp)/.sumWeight
           else !deCoeffs.(index) <- 0.0;
           setDeCoeffs x (y+.1.0) (index+1) sumWeight)
       else
         (if x<max_rad then setDeCoeffs (x+.1.0) 0.0 index sumWeight else index)
    in
    if pos<max_index_count then
      createFilter (pos+1) (setDeCoeffs 0.0 0.0 cIndex (sumGauss (1.0-.max_rad) (1.0-.max_rad) 0.0))
    else ()
  in
createFilter 0 0

として配列の各要素にアクセスする処理があります。
greenSではdeConf.(0) = 9.0, conf.(2) = 1.0なのでsetDeCoeffsのループは 1 + 2 + ... + 10 = 55 回まわることが
期待されますが、現在のアーキテクチャでは9.0*1.0 = 9.000001(+1ulp)となるので、ループが66回まわってしまい、
配列外にアクセスして動作がおかしくなります。

ただ、これをシミュレータで誤魔化して試しに動かして見たところ、やはり無限ループに入ってしまいました。
今度の原因はsinやint_of_floatなどの引数にnanが現れていることでした。
現在はこれらに対応しようとしているところです。とりあえず今までの成果はcompiler_bug_fixにあげてあります。

**Comment by tomykaira** [comment]
了解しました。どのみちコアは地下があくまで動けないので、ゆっくりやってください。

**Comment by urabenatsuki** [comment]
対応が非常に遅れて申し訳ありませんでした。

前述の通り、exp,sinを大きい数に対応させ、累乗を修正し、
sin,int_of_floatを引数にnanが来たときに特別な処理を行うように改造した上で、
fmulが整数の乗算については1ulpも違わない答えを返すようにシミュレータで処理させて実行してみたのですが、
今度はfsqrtに負値が渡されてエラーとなってしまいました。

原因は-nan \* -nan = -nan となっていたことでした。
greenSをocamlで実行してみても非正規化数同士の掛け算は大量に発生しました。

また、シミュレータでの実行中にも
  fsqrt 2139095040 should 2139095040 but answer 1602224128
というようなメッセージがいくつも出力されています。

したがって、greenSを実行するにはfmulが整数同士については正確な答えを返すようにすることと、
FPUを非正規化数に対応させることが必要そうで、ソフトでは対応できそうにありません。
