### ISSUE TITLE
tomykaira 製コンパイラを統合

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/mips#7]
一応立てておきます。

**Comment by urabenatsuki** [comment]
一応マージはしました。
ただ,min-rtを動かそうとすると配列のインデックスにすごく大きな値を与えて止まってしまうので,
どこかにバグがあるものと思われます。
これから修正します。
ソースコードはとりあえず自分のforkにあげてあります。

**Comment by tomykaira** [comment]
ありがとうございます。
もし必要であれば確認手伝います。

この作業がおわったら、FractalFlame から作成したテストケースでいくつか問題がみつかったので、
それらが新しいものでも存在するかを確認する作業をおねがいします。
もちろん私も平行でやりますが、たぶん自分だけでは分からない部分があるので、ご協力おねがいします。
